name: Rerun failed testing farm tests
on:
  issue_comment:
    types: [created]
permissions:
  contents: read
# The concurrency key is used to prevent multiple workflows from running at the same time
concurrency:
  # group name contains reponame-pr_num to allow simualteneous runs in different PRs
  group: bad-testing-farm-${{ github.event.repository.name }}-${{ github.event.issue.number }}
  cancel-in-progress: true
jobs:
  retest:
    # PR comments where a Member types "/retest" exactly
    if: |
      github.event.issue.pull_request
      && github.event.comment.body == '[citest_bad]'
    permissions:
      actions: write # for re-running failed jobs: https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#re-run-a-job-from-a-workflow-run
    runs-on: ubuntu-latest
    steps:
      - name: Re-run failed jobs for this PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NO: ${{ github.event.issue.number }}
        run: |
          head_sha=$(gh api "repos/$REPO/pulls/$PR_NO" --jq '.head.sha')
          RUN_ID=$(gh api "repos/$REPO/actions/workflows/tft.yml/runs?per_page=1&event=pull_request&head_sha=$head_sha" | jq -r '.workflow_runs[] | .id')
          gh api --method POST repos/$REPO/actions/runs/$RUN_ID/rerun-failed-jobs
