name: Schedule test on Testing Farm
on:
  issue_comment:
    types:
      - created
permissions:
  contents: read
  # This is required for the ability to create/update the Pull request status
  statuses: write
# The concurrency key is used to prevent multiple workflows from running at the same time
concurrency:
  group: my-concurrency-group
  cancel-in-progress: true

jobs:
  get_platforms:
    name: Get supported platforms from meta/main.yml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: "refs/pull/${{ github.event.issue.number }}/head"

      - name: Install yq
        run: sudo apt install -y git

      - name: Check if role supports platform ${{ matrix.platform }}
        id: supported_platforms
        run: |
          supported_platforms=""
          if yq '.galaxy_info.galaxy_tags[]' main.yml | grep -qi fedora; then
            supported_platforms+=" Fedora-39"
            supported_platforms+=" Fedora-40"
          fi
          if yq '.galaxy_info.galaxy_tags[]' main.yml | grep -qi el7; then
            supported_platforms+=" CentOS-7-latest"
          fi
          if yq '.galaxy_info.galaxy_tags[]' main.yml | grep -qi el8; then
            supported_platforms+=" CentOS-Stream-8"
          fi
          if yq '.galaxy_info.galaxy_tags[]' main.yml | grep -qi el9; then
            supported_platforms+=" CentOS-Stream-9"
          fi
          echo "supported_platforms=$supported_platforms" >> $GITHUB_OUTPUT

  testing-farm:
    name: ${{ matrix.platform }}/ansible-${{ matrix.ansible_version }}
    needs: get_platforms
    # Let's schedule tests only on user request. NOT automatically.
    # Only repository owner or member can schedule tests
    if: |
      github.event.issue.pull_request
      && (contains(github.event.comment.body, '[test]') || contains(github.event.comment.body, '[test-all]'))
      && contains(fromJson('["OWNER", "MEMBER"]'), github.event.comment.author_association)
      && contains(${{ needs.get_platforms.outputs.supported_platforms }}, ${{ matrix.platform }}) 
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: Fedora-39
            ansible_version: 2.17
          - platform: Fedora-40
            ansible_version: 2.17
          - platform: CentOS-7-latest
            ansible_version: 2.9
          - platform: CentOS-Stream-8
            ansible_version: 2.9
          - platform: CentOS-Stream-8
            ansible_version: 2.17
          - platform: CentOS-Stream-9
            ansible_version: 2.17
    runs-on: ubuntu-latest
    steps:
      - uses: sclorg/testing-farm-as-github-action@v2
        with:
          git_url: https://github.com/spetrosi/tft-tests
          git_ref: add-tmt-tests
          tmt_path: plans/
          pipeline_settings: '{ "type": "tmt-multihost" }'
          # variables: "ANSIBLE_VER=${{ matrix.ansible_version }};REPO_NAME=${{ github.event.repository.name }};PR_NUM=${{ github.event.issue.number }}"
          variables: "ANSIBLE_VER=${{ matrix.ansible_version }};REPO_NAME=${{ github.event.repository.name }}"
          pull_request_status_name: ${{ matrix.platform }}/ansible-${{ matrix.ansible_version }}
          compose: ${{ matrix.platform }}
          # Using private scope and RH ranch because multihost is not supported in public so far.
          # https://github.com/teemtee/tmt/issues/2620
          tf_scope: private
          api_key: ${{ secrets.TF_API_KEY_RH }}
          update_pull_request_status: true